### PR TITLE
Fix #35: overlapblock Creator - Web design

### LINKED ISSUE #35: Delete so unnecessary pages
We have discovered that we have too many test pages on the "pages" folder.

So you Goal is to delete the following files:

feature_all_test.html
feature_tet.html

### PR DESCRIPTION
**Pull request by viprajtelukoti**
Fixed overlapblock issue #35

Screenshot 2023-11-13 at 1 29 16 PM

### CODE REVIEW

**Comment by viprajtelukoti** [comment]
@NtemKenyor 
Can you please check the PR.

Thanks

**Comment by NtemKenyor** [comment]
okay thank you for sending in a PR, Would review and accept within the
week.

Thank you.

**Review by NtemKenyor — APPROVED** [review]
Thank you for your Contribution to the Kwickerhub project. We are glad to have you here. 

The good news is that we are building step by step and gradually, We would be the largest open source web development tool. We have activated our sponsorship buttons and we encourage you to try sponsoring this project (If you can...). We have made arrangements to release our first GPT in few weeks from now. An AI tool that can create interesting web modules for you 👍.

Once again, Thank you 💕 and congratulations 👏

You're our Hero 🙏❤️

**Comment by viprajtelukoti** [comment]
Dear Ntem Kenyor K. and the Kwickerhub Team,

Thank you from the bottom of my heart for your incredibly kind and uplifting message. I'm truly honored to be a part of the Kwickerhub project and to contribute to its growth and success.

It's truly exciting to hear about the progress the team is making, step by step, towards becoming the largest open source web development tool. The activation of sponsorship buttons is fantastic news, and I'm more than willing to support this project in any way I can. The vision of Kwickerhub as the leading open source web development tool is inspiring, and I believe in the positive impact it will have on the developer community.

The announcement of the upcoming release of the first GPT in a few weeks is incredibly thrilling! An AI tool that can generate interesting web modules is a game-changer, and I can't wait to experience its capabilities.

Once again, thank you for the heartfelt recognition and congratulations. Being called a hero by the Kwickerhub team is an absolute honor. I'm committed to continuing my contributions and supporting the growth of Kwickerhub in every possible way.

Best regards,
Vipraj Telukoti

**Pull request merged**
