### PR TITLE
Update dashboard.html

### PR DESCRIPTION
**Pull request by johnwinifred**
**Adding Block Html Comment in dashboard.html **
The aim of this is improve the project's maintainability regardless of who may work on it in future.

1. I highlighted some changes that should be made for better user experience and suggested Bootstrap, a framework that improves responsiveness.
2. I used the assigned classnames and id to map out points where changes have to be made.
3. I commented out sections in dashboard.js that were left unchanged by the action on line #110.

### CODE REVIEW

**Review by NtemKenyor — CHANGES_REQUESTED** [review]
Hello 👋

This is some great contribution and it contains a lot of details. I must confess, Must of the things you listed in the comment section are stuffs we are planning to do already.

However the issue you are trying to solve is a lot more simple. All we needed in the comment section was the comment below

```
    <!-- <head>
        <title> #Particular Project Name</title>
        <script>
            //Plugin Start
            //##
            //Plugin End 
        </script>
    </head> -->
```
As strange as that looks, We need it to control the variables that are needed for each project. 
**Best Way**
The best way to solve this issue is to look for the function that clears the entire content of the development dashboard and adds the first element. (check dashboard.js). Look for innerHTML and make sure that the innerHTML of the development dashboard is set to your comment.

```
//Before 
dashboard.innerHTML = "";

//After your Contribution
var your_comment = "
    <!-- <head>
        <title> #Particular Project Name</title>
        <script>
            //Plugin Start
            //##
            //Plugin End 
        </script>
    </head> -->";
dashboard.innerHTML = your_comment;

```
This approach is the best because all the content in the development dashboard is erased at the creation of the first project element. And we need the comment to remain through out the project.
Hope you now understand clearly?
For the main time, I will be copying your comments here as you will see more issues of that kind before the end of this week 😊 🙏

Just make that adjustment and let me approve.

You are free to ask questions.

**Comment by johnwinifred** [comment]
Okay Got it 👌

**Comment by NtemKenyor** [comment]
Ok. That;s good to know. And don't feel shy to try anything, the worse thing that can happen is that you get corrected and you become more knowledgeable about the project.

**Comment by NtemKenyor** [comment]
@johnwinifred this is the section of the code you need to locate and change in dashboard.js
Screenshot from 2022-10-09 20-26-16

I have even changed the file for you. I will be closing this pull request and i will need you to follow my example below. and send another pull request. I used `` to quote the string not "" or ''
Screenshot from 2022-10-09 20-30-23


thank you and Good luck

**Pull request closed without merging**
