### PR TITLE
table Creator - Web design #34 

### PR DESCRIPTION
**Pull request by hemantchaurasia2002**
I used simple HTML and CSS to make this table.

### CODE REVIEW

**Comment by hemantchaurasia2002** [comment]
Please merge.

**Comment by hemantchaurasia2002** [comment]
**grid Creator - Web design #348**
I created a gridbox according to the given instructions - 
image

**Review by NtemKenyor — APPROVED** [review]
We're so impressed with your contribution to our open source project. It's clear that you have a deep understanding of our code and a passion for making it better.

Thank you 💕 and Congratulations 🎉

**Comment by hemantchaurasia2002** [comment]
Thanks for merging 👍

**Pull request merged**
