### PR TITLE
UI of card-5 completed

### PR DESCRIPTION
**Pull request by Notoriousbrain**

### CODE REVIEW

**Review by NtemKenyor — CHANGES_REQUESTED** [review]
Hello and thank you for contributing. Before I accept, I need you to make some few changes.
No need for the head section as this module is suppose to be easily reusable by other designers. Please remove the head section and the body tag. we only need three(or less than 3 tags) that includes: "div", "style", "script" tag. You can check the accepted pull request for button designs.

thank you. You can drop a message whenever you need more info.

**Comment by Notoriousbrain** [comment]
I have made the changes.

**Review by NtemKenyor — CHANGES_REQUESTED** [review]
**Missed something - One Last Change would do**

Hello and hope you are doing great. 

Great job so far. However, I am going to drop a code sample for you as to make it very easy to understand. Remove any html or Doctype tag, the main project would already have that. Do not create multiple files for your module except in extremely unique cases(Which this is not..)... 
Also, Avoid styling the general tags(body, head, html etc) as this would affect the entire project. Don't style or add scripts to anything outside your parent/first "div".  The goal is to make a module that is simple, dynamic and easily reusable.

card_NUM_(YOUR_NAME).html
```
<!---- Your styling would enter inside the style tag ----->
<style>

</style>

<!---- All scripts would enter inside the script tag ----->
<script>

</script>
<!---- Normal HTML Flow ----->
<div>
    <div class="center-div">
    ...
    </div>
</div>
```

Thank you.

**Comment by Notoriousbrain** [comment]
I have done the exact format you wanted.

**Review by NtemKenyor — APPROVED** [review]
Thank you for your contribution and support to open source development. We are grateful. Once again: Thank you. We are sorry for the delay. Info: We are very active at the moment because of the Open source event coming up( Hacktoberfest ). Congratulations.

**Pull request merged**
