### PR TITLE
OVERLAPBLOCK_Design_14#247

### PR DESCRIPTION
**Pull request by jais-rishika**
OVERLAPBLOCK (DESIGN 14) Issue https://github.com/KwickerHub/frontend/issues/247
I have created an overlap block that looks like the button in the given image.
If some changes required kindly tell I'll do it.

### CODE REVIEW

**Comment by NtemKenyor** [comment]
@jais-rishika that issues was not about creating a button but about creating that entire overlapblock design.(Design the entire image as seen in that issue. Make it responsive for desktop, mobile and tablets as you design.)

Hope you understand? and by the way, Hope you are doing great?

**Comment by jais-rishika** [comment]
Yes!! Then I'll do that then. 
About the images where to get the exact images or can i add any suitable one.
Thanks, I'm doing great :)

**Comment by NtemKenyor** [comment]
Hello 👋
Hope you are in good shape?

Please feel free to use other images. But avoid using external url images.
The different categories of modules have a section for image upload(If it
does not exist, U can create the folder inside that particular module).
Check buttons modules for insights...

Thanks...

**Comment by jais-rishika** [comment]
OVERLAPBLOCK_Design_14#247 #261
I have created an overlap block like the given image.
I have added 4 images in OVERLAP_DESIGN_14_images folder in  modules\image_carousel\images_and_icons\OVERLAP_DESIGN_14_images
If some changes required kindly tell I'll do it.

**Review by NtemKenyor — APPROVED** [review]
wow. Good one.

Thank you for your contribution to open source development. Congratulations.

**Pull request merged**
