### PR TITLE
fixed setting popup for mobile view

### PR DESCRIPTION
**Pull request by ShreyasSahoo**
Please assign me this issue under hacktoberfest label.

### CODE REVIEW

**Comment by ShreyasSahoo** [comment]
Hey NtemKenyor, could you review this PR . Also please do tell me if it needs further changes.

**Comment by NtemKenyor** [comment]
Oh. Sorry for the delay. I will approve and assign to you after I review. Little patience pls...

**Review by NtemKenyor — COMMENTED** [review]
_unrelated message..._

**Comment by NtemKenyor** [comment]
please ignore the previous message

**Review by NtemKenyor — APPROVED** [review]
I was thinking we could rearrange the styles in the dashboard.css file and make only one media query for mobile. 

However, your code looks great. thank you.

**Pull request merged**
