### PR TITLE
creating youtube_button v2

### LINKED ISSUE #166: Youtube Button - Session of Buttons
Inline with our "session of Buttons", We would be building different kinds of buttons..

Design a Button that looks like the button in this image...

Create a file "Your_Button_Name.html" in the modules/buttons folder.

Use simple HTML and CSS to create the button. You can use the interface development https://kwickerhub.com (This project) or you can code it.
For some additional info, You should read the instructions.txt file in "buttons" folder.
Screenshot from 2023-04-14 12-56-19

### PR DESCRIPTION
**Pull request by royninja**
as there was issue in #189 so this is the latest version

Closes #166 

232247552-51cc686b-0e76-490f-83ee-5faaf15e9ce1

### CODE REVIEW

**Review by NtemKenyor — APPROVED** [review]
I like your naming style. is that a nickname or do you mean version 2. LOL. Anyways, it's all good. Thank you for contributing to KWICKERHUB development.

**Comment by royninja** [comment]
I mean it's a version as there was a conflict with the version 1 so that's the reason

**Comment by NtemKenyor** [comment]
Ok. I'm thinking🤔, In the future, We may need to make modules with
different versions and newly added stuff. e.g Mobility, Flexibility etc

**Comment by NtemKenyor** [comment]
But it's all good. Do have a nice day...

**Pull request merged**
