### PR TITLE
Fixed issue #132

### PR DESCRIPTION
**Pull request by kull-boii**
added event listener to call removeSelected() function when delete key is pressed.

### CODE REVIEW

**Comment by kull-boii** [comment]
prettier just formatting the code :/

**Comment by kull-boii** [comment]
@NtemKenyor ??

**Review by NtemKenyor — CHANGES_REQUESTED** [review]
Hello @kull-boii 

hope you are doing great? Sorry for the delay. Please I need you to stop "prettier" from editing your lines of code as that will affect others working in this file. And I can't really see the specific areas you made the adjustment because I can see over 300 changes.

Please fix that. By the way, You have are a great contributor to Open Source Development (KwickerHub). Thank you.

**Review by NtemKenyor — APPROVED** [review]
thank you for your contribution.

**Pull request merged**
