### PR TITLE
add styles to profile page

### PR DESCRIPTION
**Pull request by epolis185**

### CODE REVIEW

**Comment by Ezekiel8807** [comment]
please assign this to me i will love to work on it

**Comment by Ezekiel8807** [comment]
with the label hacktoberfest

**Comment by epolis185** [comment]
Hi @Ezekiel8807, this is a pull request with styles that I added to the profile page. You would want to check out issues here: [https://github.com/KwickerHub/frontend/issues](url) to work on and contribute to the project

**Comment by NtemKenyor** [comment]
Really funny. LOL Though that's the spirit man. Keep looking for ways to contribute.

**Review by NtemKenyor — APPROVED** [review]
Thanks for contributing.

**Pull request merged**
