### PR TITLE
Added name as contributor in aboutus.html

### PR DESCRIPTION
**Pull request by ProtyayMnd50**
Added my name in our contributors in aboutus.html

### CODE REVIEW

**Comment by ProtyayMnd50** [comment]
Could you pls review my pr @NtemKenyor? Do tell me if you need any changes .If valid for merge, merge it with hacktober-accepted tag.

**Review by NtemKenyor — COMMENTED** [review]
Could you append your name in the table? If you can't see the table in the about_us.html, U may have to pull from upstream. Pls give me feedback

**Comment by ProtyayMnd50** [comment]
Ok , will do that

**Comment by ProtyayMnd50** [comment]
Could you pls review it again @NtemKenyor ?

**Review by NtemKenyor — APPROVED** [review]
Looks great. Thank you.

**Pull request merged**
