### PR TITLE
Fixed text_on_image Creator - Web design #147 #647

### PR DESCRIPTION
**Pull request by grnitish**
Added files in text_on_image and added image in images_and_icons.

### CODE REVIEW

**Comment by grnitish** [comment]
@NtemKenyor could you please review it.

**Comment by grnitish** [comment]
@NtemKenyor could you please review, cause I've to do 4 git contributions as part of our course.

**Review by NtemKenyor — APPROVED** [review]
thank you very much for contributing

**Comment by NtemKenyor** [comment]
### Congratulations

I hope this message finds you well. I am writing to express our sincere gratitude for your recent contribution to our open source project. Your commitment to the project has not only enhanced its functionality but has also demonstrated the spirit of collaboration that makes open source communities thrive.

Congratulations on your exceptional work! Your dedication and expertise have significantly contributed to the success of our project, and we are truly fortunate to have you as part of our community.

I must extend my sincere apologies for the delayed response to your pull request. We deeply appreciate your patience and understanding. As our project continues to grow, we recognize the need to improve the quality and response time for contributions. To achieve this, we have initiated a call for maintainers and reviewers who can help us maintain the high standards of the project and ensure timely responses to pull requests.

Your involvement and insights would be invaluable in this endeavor. If you or anyone you know is interested in taking on a more active role in the project, please don't hesitate to reach out. We believe that with a strong team of maintainers and reviewers, we can enhance both the quality of the project and the speed of our responses.

Additionally, I am pleased to inform you that we have activated the sponsorship button for our project. This is an exciting development that allows supporters like you to contribute to the sustainability and growth of the project. Your continued support, whether through code contributions or sponsorship, is truly appreciated.

Once again, congratulations on your outstanding contribution, and thank you for being an essential part of our open source community. We look forward to your continued collaboration and success together.

Best regards,

Ntem, KenyorK.
Lead
Kwickerhub

**Pull request merged**
