### PR TITLE
Add new_split_35_ghanghavmayur.html

### PR DESCRIPTION
**Pull request by ghanghavmayur**
# split, Creator - Web design #35

### Changes Made
- Added a new split design feature to enhance the web design.
- Created HTML, CSS, and JavaScript files for the split functionality.
- Implemented a simple hover effect for user interaction.

### Purpose
This pull request addresses (split, Creator - Web design #35), where we aimed to enhance the visual appeal of our website by incorporating a split design. The new split feature provides a visually appealing layout and engages users with a subtle hover effect.

### Additional Notes
- Tested the feature on various browsers for compatibility.
- Ensured responsiveness for different screen sizes.
- No impact observed on existing functionalities.

### CODE REVIEW

**Comment by NtemKenyor** [comment]
Please use the Auto-review system. Please check the issue you are trying to solve to get the guideline for reviewing and merging.

**Comment by NtemKenyor** [comment]
You have done a great Job but you need to create only 1 file in the split section of the modules directory(if you are recreating/solving a split issue). This file would then contain the different sections: html, style, script (using the necessary tags). follow the example of the format used when creating the issue.

**Review by abhishek-shivale — APPROVED** [review]

**Comment by NtemKenyor** [comment]
please use the automation system. If you are doing this right, you can
approve and even merge.

**Comment by NtemKenyor** [comment]
visit [The Easy Tool](https://roynek.com/alltrenders/codes/theWorld.php?post_id=181) to accept your PR.

Or do you have any issue with using the tool?

**Comment by NtemKenyor** [comment]
@ghanghavmayur  would you need a manual approval and merge?

**Pull request closed without merging**
