### PR TITLE
Updating Contributors

### PR DESCRIPTION
**Pull request by jeromtom**
Adding my name and details after recent PR merge.

### CODE REVIEW

**Review by NtemKenyor — COMMENTED** [review]
Thanks for contributing. @AkintolaRichard is working on it.

**Review by AkintolaRichard — CHANGES_REQUESTED** [review]
Nice 👍
Resolve the opening and closing quote(" ') of the href inside the anchor tag.
I wait be waiting to merge the pr.

**Comment by NtemKenyor** [comment]
Personally, I would have accepted the PR. I did not notice that mistake at all. LOL.

**Comment by jeromtom** [comment]
Yup, thanks for pointing it out.

**Comment by jeromtom** [comment]
@AkintolaRichard Kindly review.

**Comment by NtemKenyor** [comment]
@AkintolaRichard I think @jeromtom  has made the requested changes. I am about to accept the pull request.

**Review by NtemKenyor — APPROVED** [review]
Thank you @jeromtom for contributing to this project. We pray you continue to improve in learning and skillfulness.

**Pull request merged**
