### PR TITLE
Fix Issue #212: CLICK_HERE_BUTTON

### PR DESCRIPTION
**Pull request by nicholasboyce**
#212 
Styled 'Click Here' button in the manner of the reference image in modules/buttons/images_and_icons/reference_image.png. Could not find a way to cleanly imitate arrow pointer in the example. Added SVG image downloaded online from open source website as a fix. 

Please let me know if there are cleaner/more acceptable ways to complete this task. I am open to improving and always looking for constructive feedback! I hope that my contribution can be in someway useful. Thank you.

### CODE REVIEW

**Comment by nicholasboyce** [comment]
Screen Shot 2023-04-26 at 9 55 24 PM
Please see resulting button above as well.

**Review by NtemKenyor — CHANGES_REQUESTED** [review]
your solution looks great. However, no need to declare "<!DOCTYPE>" and "<html>". Non-English users would also be using your design.

Observe other examples or accepted button designs. Please, Remove the html tag just start from div tag.

I am now available to accept any Pull request.

**Review by NtemKenyor — CHANGES_REQUESTED** [review]
Great Job but please remove the Doctype and html tag. Start from the div tag. You can check other accepted buttons.

I am available to accept your PR.

**Comment by nicholasboyce** [comment]
Thank you for your feedback! I've removed the DOCTYPE and HTML tag as you requested and created a new commit. Please let me know if there is anything else I can fix.

**Review by NtemKenyor — APPROVED** [review]
Thank you for your contribution to Kwickerhub ❤️👍

**Pull request merged**
