### PR TITLE
added: web design #23

### PR DESCRIPTION
**Pull request by hemantchaurasia2002**
table Creator - Web design #23

### CODE REVIEW

**Comment by hemantchaurasia2002** [comment]
@NtemKenyor please review my code

**Comment by hemantchaurasia2002** [comment]
Please take a look at my pull request.
I have to complete Hacktoberfest 2023 and only 6 days letf 🙏
@NtemKenyor

**Comment by NtemKenyor** [comment]
> Please take a look at my pull request. I have to complete Hacktoberfest 2023 and only 6 days letf 🙏 @NtemKenyor

Please easy on me, I only have time to attend to Pull request after work. I am glad you have made a PR and I am on it right now... thank you.

**Review by NtemKenyor — APPROVED** [review]
Thank you for your invaluable contributions to Kwickerhub! Your dedication to our open-source project is deeply appreciated. We're excited to inform you about our new sponsorship button, allowing supporters like you to further enhance the project's success. Together, we're shaping a brighter future for Kwickerhub!

Once again: Thank you and Congratulations

**Pull request merged**
