### PR TITLE
table Created of Web design #352

### PR DESCRIPTION
**Pull request by Aka-suvam**
Created table with only HTML & CSS.  
Screenchot of Table  #352 .  let me know if anything requires changes.

Screenshot of table-1

### CODE REVIEW

**Comment by Aka-suvam** [comment]
Sorry i made  a  mistake . when i  was making a PR for the issue - #352   i mention  the wrong issue num which is - (table Created of Web design KwickerHub#1)   in the commit . 
but i also correct it  this is correct one - (table Created of Web design KwickerHub#352).

**Comment by NtemKenyor** [comment]
> Sorry i made a mistake . when i was making a PR for the issue - #352 i mention the wrong issue num which is - (table Created of Web design #1) in the commit . but i also correct it this is correct one - (table Created of Web design #352).

Okay. It is understood...

**Review by NtemKenyor — APPROVED** [review]
We are deeply grateful for your support and contributions in make our Open Source Project great 🎉.

You have made an awesome contribution to Kwickerhub. 😊 Thank you 💕

**Comment by Aka-suvam** [comment]
Thank you! . i also  learn a lot through the contributions on your repos and also like the Repo issues ideas .

**Pull request merged**
