### PR TITLE
OVERLAPBLOCK (DESIGN 19) #252

### PR DESCRIPTION
**Pull request by AggarwalNeelesh**
OVERLAPBLOCK (DESIGN 19) Issue #252

I have created an overlap block that looks like the button in the given image.

### CODE REVIEW

**Review by MaverickDe — CHANGES_REQUESTED** [review]
You are to recreate the whole design not only the button

**Comment by AggarwalNeelesh** [comment]
> You are to recreate the whole design not only the button

Okay, I will do it, 
Can you send me higher resolution image of it ?

**Comment by NtemKenyor** [comment]
I'm not sure @MaverickDe has a higher resolution but creating something similar with your own custom images still does the trick👍...

**Comment by AggarwalNeelesh** [comment]
Okay got it

**Comment by NtemKenyor** [comment]
Thank you. We would be closing this. Your file looks more like a button but it's in overlapping blocks. If you want to make a PR for an overlap, U have to design everything (The entire screen). Else add your contribution to the button section.

**Pull request closed without merging**
