### PR TITLE
fixed the UI of the nav button on mobile view

### PR DESCRIPTION
**Pull request by JohnnyOhms**
Request to issue #135, fixed the nav drop down bug on mobile view to avoid obstruction on "Design Developed" header.

**Before Screenshot of issue**
Notice - officialjohn662@gmail com - Gmail - Google Chrome 12_13_2022 3_31_54 PM (2)

**After Screenshot of issue fixed**
Notice - officialjohn662@gmail com - Gmail - Google Chrome 12_13_2022 3_39_06 PM (2)

### CODE REVIEW

**Review by NtemKenyor — CHANGES_REQUESTED** [review]
Hope you are doing great. I'm really sorry for keeping your pull request for this long.
I observed that you made about 5 to 10 lines of additional code but the total changes on this file is about +456.

This usually happens when you have a software that helps in rearranging your lines of code. It is a good software for your personal jobs but it may cause some problem for other developers working on that same file in an Open source Project.

Please,reset HEAD or Re-clone the Project and stop the software from rearranging our lines of code in VS-code and remake the pull request. 

If you do not understand any of the things I have just said, Feel free to drop some comment for better explanation. thank you.

**Comment by JohnnyOhms** [comment]
No problem, working on it.

**Comment by NtemKenyor** [comment]
Hello @JohnnyOhms hope you are doing great. We have observed that your contributions will go a long way to help our open source project, From the screenshots you sent here, we believe that is a feature(Bug fix) we truly need. We are waiting patiently to hear from you. and we will be reopening this Pull Request. All we need from you is your index.css contribution and not more.

Thank you for understanding.

**Comment by NtemKenyor** [comment]
@JohnnyOhms I feel this commands may help you.

git reset --hard online_repo/<branch>
git reset --hard upstream/dev

then adjust the index.css file and git push to your origin repo. Then come on github and make the pull request

Or 

Clone the project again in another folder and use a TextEditor that will not auto-change tools or indexes for you. add your code in index.css and git push to your origin as to make the pull request. When ever you are ready... We will be ready.

**Comment by JohnnyOhms** [comment]
Ok sure I understand @NtemKenyor

**Pull request closed without merging**
