### PR TITLE
Contributed to aboutus.html

### PR DESCRIPTION
**Pull request by tab21**
Added tab21 as contributor

### CODE REVIEW

**Review by NtemKenyor — DISMISSED** [review]
Thank you for adding your name to the book of histories. Well done.

**Comment by NtemKenyor** [comment]
Pls

Use the command
git pull upstream dev

and resolve the conflicts because many people were trying to append their names too but you make your pull request.

**Review by NtemKenyor — CHANGES_REQUESTED** [review]
make sure your branch is up-to date with the upstream before sending us a pull request. Please just work on that and we will be more than happy to accept your name.

**Comment by tab21** [comment]
I think it should be fine now ?

**Review by NtemKenyor — APPROVED** [review]
Well done.

**Pull request merged**
