### PR TITLE
Fixed Issue: text_on_image_96_by_rahulchanumolu

### PR DESCRIPTION
**Pull request by rahulchanumolu**
#596 

fixed issue by rahulchanumolu.

### CODE REVIEW

**Review by NtemKenyor — CHANGES_REQUESTED** [review]
I would love to accept this PR but please remove all this hidden files example: modules/overlapblock/images_and_icons/.main.jpg.icloud

I would even love it if you make it possible for git to ignore all hidden files. I have raised an issue for that.

**Comment by NtemKenyor** [comment]
We would accept your PR in few days from now if you do not respond as to fix this but we would accept it immediately if you respond. 

We may have to create a team to fix it. Thank you.

**Comment by rahulchanumolu** [comment]
I will fix all these issues by the end of the day, Thank you

**Review by NtemKenyor — CHANGES_REQUESTED** [review]
a lot of hidden files are added to your PR.

**Comment by rahulchanumolu** [comment]
I am unable to delete those I will close this PR and open a new PR.

Thank you,
Rahul C

**Pull request closed without merging**
