### PR TITLE
Fixed_issue: overlapblock Creator - Web design #17 #426

### PR DESCRIPTION
**Pull request by sahanasurapureddy**
#426

### CODE REVIEW

**Comment by sahanasurapureddy** [comment]
Hi @NtemKenyor, I have raised a PR for the above issue. Can you please look into it?

**Comment by sahanasurapureddy** [comment]
Hi @NtemKenyor please could you check my pull request and let me know if any changes need to be done, so I could work on it and update the pull request asap. I have a submission deadline coming up for my final project, and I wanted to include this issue I had worked on if my pull request gets accepted.  

Thank you so much.

**Review by NtemKenyor — APPROVED** [review]

**Comment by NtemKenyor** [comment]
Thank you for making this contribution. We are glad to have you.

**Comment by NtemKenyor** [comment]
### Congratulation

**Pull request merged**
