### PR TITLE
Changed save tool tip text and added popup

### LINKED ISSUE #41: Add description on Save Icon
**Add description on Save Icon on dashboard.html**

If you hover at the Save sub-menu under the file menu of the "dashboard.html" file, You will see a short pop-up "Tooltip text".

_Change the "Tooltip text" to "more"_

**Action(little JavaScript)**
When a user clicks on "more", He should then see a description about the save button. for instance "Use this option to save your project to the serve to avoid loss of data. ".

### PR DESCRIPTION
**Pull request by Cursed-Ninja**
Resolved #41

### CODE REVIEW

**Comment by Cursed-Ninja** [comment]
Most of the conflicts are due to spacing/tabs changes.

**Comment by Cursed-Ninja** [comment]
Resolved #79

**Review by NtemKenyor — APPROVED** [review]
Thank you for contributing to open source development.

**Comment by NtemKenyor** [comment]
@Cursed-Ninja please avoid adding too many unnecessary spaces or new lines or using a formatting software on the project when you contribute next time. Anyways, Thank you.

**Comment by Cursed-Ninja** [comment]
Alright will make sure from future. Sorry for the inconveniences, actually my code just formats itself whenever I save my code.

**Pull request merged**
