### PR TITLE
Issue#345: create table design.

### PR DESCRIPTION
**Pull request by THEFZNKHAN**
solve the Issue #345. 
Add this file for grid design

### CODE REVIEW

**Comment by THEFZNKHAN** [comment]
If anything needs to change then let me know😊.

**Comment by THEFZNKHAN** [comment]
Would you please add the "HACKTOBERFEST-ACCEPTED" label to my PR.

**Review by NtemKenyor — APPROVED** [review]
Your contribution to our open source project is like a breath of fresh air. It's helping us to take our project to the next level!

Thank you 🎉👍

**Comment by NtemKenyor** [comment]
Glanced through: Keep up the code quality.

**Comment by NtemKenyor** [comment]
We are having some issues with merging this Pull Request. Looks like it was closed from your end..

**Pull request merged**
